// @generated by scripts/generate-built-in-icons.ts — do not edit manually
import type { FileTreeBuiltInIconSet } from './iconConfig';

export type BuiltInFileIconToken =
  | 'css'
  | 'default'
  | 'git'
  | 'image'
  | 'javascript'
  | 'json'
  | 'markdown'
  | 'mcp'
  | 'npm'
  | 'react'
  | 'typescript';

const SIMPLE_SVG_SPRITE_SHEET = `<svg data-icon-sprite aria-hidden="true" width="0" height="0">
  <symbol id="file-tree-icon-chevron" viewBox="0 0 16 16">
    <path d="M12.4697 5.46973C12.7626 5.17684 13.2374 5.17684 13.5303 5.46973C13.8232 5.76262 13.8232 6.23738 13.5303 6.53028L8.53028 11.5303C8.23738 11.8232 7.76262 11.8232 7.46973 11.5303L2.46973 6.53028C2.17684 6.23738 2.17684 5.76262 2.46973 5.46973C2.76262 5.17684 3.23738 5.17684 3.53028 5.46973L8 9.93946L12.4697 5.46973Z" fill="currentcolor"/>
  </symbol>
  <symbol id="file-tree-icon-dot" viewBox="0 0 6 6">
    <circle cx="3" cy="3" r="3" />
  </symbol>
  <symbol id="file-tree-icon-file" viewBox="0 0 16 16">
    <path fill="currentcolor" d="M10.75 0c.199 0 .39.08.53.22l3.5 3.5c.14.14.22.331.22.53v9A2.75 2.75 0 0 1 12.25 16h-8.5A2.75 2.75 0 0 1 1 13.25V2.75A2.75 2.75 0 0 1 3.75 0zm-7 1.5c-.69 0-1.25.56-1.25 1.25v10.5c0 .69.56 1.25 1.25 1.25h8.5c.69 0 1.25-.56 1.25-1.25V5h-1.25A2.25 2.25 0 0 1 10 2.75V1.5z" />
  </symbol>
  <symbol id="file-tree-icon-lock" viewBox="0 0 16 16">
    <path fill="currentcolor" d="M4 5.336V4a4 4 0 1 1 8 0v1.336c1.586.54 2 1.843 2 4.664v1c0 4.118-.883 5-5 5H7c-4.117 0-5-.883-5-5v-1c0-2.821.414-4.124 2-4.664M5.5 4v1.054Q6.166 4.998 7 5h2q.834-.002 1.5.054V4a2.5 2.5 0 0 0-5 0m-2 6v1c0 .995.055 1.692.167 2.193.107.483.246.686.35.79s.307.243.79.35c.5.112 1.198.167 2.193.167h2c.995 0 1.692-.055 2.193-.166.483-.108.686-.247.79-.35.104-.105.243-.308.35-.791.112-.5.167-1.198.167-2.193v-1c0-.995-.055-1.692-.166-2.193-.108-.483-.247-.686-.35-.79-.105-.104-.308-.243-.791-.35C10.693 6.555 9.995 6.5 9 6.5H7c-.995 0-1.692.055-2.193.167-.483.107-.686.246-.79.35s-.243.307-.35.79C3.555 8.307 3.5 9.005 3.5 10" />
  </symbol>
  <symbol id="file-tree-icon-ellipsis" viewBox="0 0 16 16">
    <path d="M5 8.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0M9.5 8.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0M14 8.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0" />
  </symbol>
</svg>`;

const ft_css = `<symbol id="file-tree-builtin-file-type-css" viewBox="0 0 16 16">
  <path fill="currentColor" d="M8 1c5.765 0 7 1.236 7 7s-1.235 7-7 7-7-1.235-7-7V2a1 1 0 0 1 1-1zM4.178 5.5C2.862 5.5 2.5 6.036 2.5 8.007c0 2.043.306 2.493 1.678 2.493 1.19 0 1.476-.236 1.566-1.308h-.759c-.07.486-.223.6-.807.601-.738 0-.899-.329-.899-1.8 0-1.457.16-1.78.899-1.78.542 0 .682.116.765.637h.76C5.618 5.75 5.34 5.5 4.177 5.5m3.735 0c-1.371 0-1.67.236-1.67 1.286 0 .914.299 1.172 1.684 1.479.765.171.932.321.932.842 0 .564-.167.68-.932.68-.773 0-.96-.109-.989-.601h-.73c-.02 1.078.278 1.314 1.663 1.314 1.42 0 1.733-.25 1.733-1.393 0-1.007-.3-1.286-1.664-1.586-.786-.178-.96-.314-.96-.728 0-.479.174-.586.947-.586.675 0 .835.08.85.422h.737C9.486 5.708 9.2 5.5 7.914 5.5m3.896 0c-1.372 0-1.671.236-1.671 1.286 0 .914.3 1.172 1.684 1.479.766.171.933.321.933.842 0 .564-.167.68-.933.68-.772 0-.96-.109-.988-.601h-.732c-.02 1.078.28 1.314 1.665 1.314 1.42 0 1.733-.25 1.733-1.393 0-1.007-.3-1.286-1.664-1.586-.786-.178-.96-.314-.96-.728 0-.479.174-.586.946-.586.676 0 .836.08.85.422h.737c-.028-.921-.313-1.129-1.6-1.129"/>
</symbol>`;
const dt_css = `<symbol id="file-tree-builtin-duo-tone-css" viewBox="0 0 16 16">
  <path fill="currentColor" d="M8 15c-5.764 0-7-1.235-7-7V2a1 1 0 0 1 1-1h6c5.765 0 7 1.236 7 7s-1.235 7-7 7" class="vector" opacity=".2"/>
  <path fill="currentColor" d="M10.103 9.186h.73c.029.493.217.6.99.6.765 0 .932-.115.932-.679 0-.521-.167-.671-.933-.843-1.385-.307-1.684-.564-1.684-1.478 0-1.05.3-1.286 1.67-1.286 1.288 0 1.574.207 1.601 1.129h-.737c-.014-.343-.174-.422-.85-.422-.772 0-.946.107-.946.586 0 .414.174.55.96.728 1.365.3 1.664.579 1.664 1.586 0 1.143-.313 1.393-1.733 1.393-1.386 0-1.685-.236-1.664-1.314m-3.895 0h.73c.028.493.216.6.989.6.766 0 .933-.115.933-.679 0-.521-.167-.671-.933-.843-1.385-.307-1.685-.564-1.685-1.478 0-1.05.3-1.286 1.671-1.286 1.288 0 1.573.207 1.601 1.129h-.738c-.014-.343-.174-.422-.85-.422-.772 0-.946.107-.946.586 0 .414.174.55.96.728 1.365.3 1.665.579 1.665 1.586 0 1.143-.314 1.393-1.734 1.393-1.385 0-1.684-.236-1.663-1.314m-1.223.007h.759c-.09 1.071-.376 1.307-1.566 1.307-1.372 0-1.678-.45-1.678-2.493 0-1.971.362-2.507 1.678-2.507 1.162 0 1.44.25 1.524 1.35h-.759c-.083-.521-.222-.636-.765-.636-.738 0-.898.322-.898 1.779 0 1.471.16 1.8.898 1.8.584 0 .737-.114.807-.6"/>
</symbol>`;

const ft_default = `<symbol id="file-tree-builtin-file-type-default" viewBox="0 0 16 16">
  <path fill="currentColor" fill-rule="evenodd" d="M9.5 1a.5.5 0 0 1 .354.147l4 4a.5.5 0 0 1 .147.353v7a2.5 2.5 0 0 1-2.5 2.5h-7A2.5 2.5 0 0 1 2 12.5v-9A2.5 2.5 0 0 1 4.5 1zm-5 1A1.5 1.5 0 0 0 3 3.5v9A1.5 1.5 0 0 0 4.5 14h7a1.5 1.5 0 0 0 1.5-1.5V6h-2a2 2 0 0 1-2-2V2z" clip-rule="evenodd"/>
</symbol>`;
const dt_default = `<symbol id="file-tree-builtin-duo-tone-default" viewBox="0 0 16 16">
  <path fill="currentColor" d="M8 1v3a3 3 0 0 0 3 3h3v5.5a2.5 2.5 0 0 1-2.5 2.5h-7A2.5 2.5 0 0 1 2 12.5v-9A2.5 2.5 0 0 1 4.5 1z" class="bg" opacity=".5"/>
  <path fill="currentColor" d="M9.5 1a.5.5 0 0 1 .354.146l4 4A.5.5 0 0 1 14 5.5V6h-3a2 2 0 0 1-2-2V1z" class="fg"/>
</symbol>`;

const ft_git = `<symbol id="file-tree-builtin-file-type-git" viewBox="0 0 16 16">
  <path fill="currentColor" d="M14.736 7.377 8.624 1.264a.9.9 0 0 0-1.276 0L6.08 2.534l1.61 1.61a1.071 1.071 0 0 1 1.356 1.365l1.552 1.552a1.07 1.07 0 0 1 1.109 1.771 1.074 1.074 0 0 1-1.751-1.167L8.507 6.218v3.809a1.073 1.073 0 1 1-.882-.032V6.152a1.074 1.074 0 0 1-.582-1.407L5.455 3.157l-4.191 4.19a.903.903 0 0 0 0 1.276l6.113 6.113a.903.903 0 0 0 1.275 0l6.084-6.084a.903.903 0 0 0 0-1.275"/>
</symbol>`;
const dt_git = ft_git.replaceAll(
  'file-tree-builtin-file-type-git',
  'file-tree-builtin-duo-tone-git'
);

const ft_image = `<symbol id="file-tree-builtin-file-type-image" viewBox="0 0 16 16">
  <path fill="currentColor" d="M5.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3"/>
  <path fill="currentColor" fill-rule="evenodd" d="M12.5 2A2.5 2.5 0 0 1 15 4.5v7a2.5 2.5 0 0 1-2.5 2.5h-9A2.5 2.5 0 0 1 1 11.5v-7A2.5 2.5 0 0 1 3.5 2zm-9 1A1.5 1.5 0 0 0 2 4.5v6.917L4.5 8.5 7 11l3.5-4.5L14 10V4.5A1.5 1.5 0 0 0 12.5 3z" clip-rule="evenodd"/>
</symbol>`;
const dt_image = `<symbol id="file-tree-builtin-duo-tone-image" viewBox="0 0 16 16">
  <path fill="currentColor" d="M15 11.5a2.5 2.5 0 0 1-2.5 2.5h-9A2.5 2.5 0 0 1 1 11.5v-7A2.5 2.5 0 0 1 3.5 2h9A2.5 2.5 0 0 1 15 4.5z" class="bg" opacity=".2"/>
  <path fill="currentColor" d="M15 10.5v1a2.5 2.5 0 0 1-2.5 2.5h-9a2.5 2.5 0 0 1-2.457-2.044L4 9l3 2 4-4zm-7-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0"/>
</symbol>`;

const ft_javascript = `<symbol id="file-tree-builtin-file-type-javascript" viewBox="0 0 16 16">
  <path fill="currentColor" fill-rule="evenodd" d="M8 1c5.765 0 7 1.236 7 7s-1.235 7-7 7-7-1.235-7-7 1.236-7 7-7M6.282 5.09v4.302c0 .837-.17 1.017-.944 1.017-.693 0-.847-.162-.847-.918h-.989c-.027 1.485.306 1.809 1.862 1.809 1.566 0 1.908-.333 1.908-1.872V5.09zM10.313 5c-1.773 0-2.16.297-2.16 1.62 0 1.152.387 1.476 2.178 1.863.99.216 1.206.405 1.206 1.062 0 .71-.216.855-1.206.855-.999 0-1.242-.135-1.278-.756h-.945c-.027 1.358.36 1.656 2.15 1.656 1.837 0 2.242-.315 2.242-1.755 0-1.269-.387-1.62-2.151-1.998-1.017-.225-1.242-.396-1.242-.918 0-.603.225-.738 1.224-.738.873 0 1.08.099 1.098.53h.954C12.347 5.262 11.978 5 10.313 5" clip-rule="evenodd"/>
</symbol>`;
const dt_javascript = `<symbol id="file-tree-builtin-duo-tone-javascript" viewBox="0 0 16 16">
  <path fill="currentColor" d="M8 1C2.236 1 1 2.236 1 8s1.236 7 7 7 7-1.235 7-7-1.235-7-7-7" class="bg" opacity=".2"/>
  <path fill="currentColor" d="M8.108 9.644h.945c.036.621.279.756 1.278.756.99 0 1.206-.144 1.206-.855 0-.657-.216-.846-1.206-1.062-1.791-.387-2.178-.711-2.178-1.863 0-1.323.387-1.62 2.16-1.62 1.665 0 2.034.261 2.07 1.422h-.954c-.018-.432-.225-.531-1.098-.531-.999 0-1.224.135-1.224.738 0 .522.225.693 1.242.918 1.764.378 2.151.729 2.151 1.998 0 1.44-.405 1.755-2.241 1.755-1.791 0-2.178-.297-2.151-1.656m-4.607-.153h.99c0 .756.153.918.846.918.774 0 .945-.18.945-1.017V5.09h.99v4.338c0 1.539-.342 1.872-1.908 1.872-1.557 0-1.89-.324-1.863-1.809"/>
</symbol>`;

const ft_json = `<symbol id="file-tree-builtin-file-type-json" viewBox="0 0 16 16">
  <path fill="currentColor" d="M2.75 4.75A2.75 2.75 0 0 1 5.5 2H6a.75.75 0 0 1 0 1.5h-.5c-.69 0-1.25.56-1.25 1.25v1.496a1.75 1.75 0 0 1-1.27 1.682L2.73 8l.25.072a1.75 1.75 0 0 1 1.27 1.682v1.496c0 .69.56 1.25 1.25 1.25H6A.75.75 0 0 1 6 14h-.5a2.75 2.75 0 0 1-2.75-2.75V9.754a.25.25 0 0 0-.181-.24l-.544-.155a1.413 1.413 0 0 1 0-2.718l.544-.155a.25.25 0 0 0 .181-.24zm6.5-2A.75.75 0 0 1 10 2h.5a2.75 2.75 0 0 1 2.75 2.75v1.496c0 .111.074.21.181.24l.544.155a1.413 1.413 0 0 1 0 2.717l-.544.156a.25.25 0 0 0-.181.24v1.496A2.75 2.75 0 0 1 10.5 14H10a.75.75 0 0 1 0-1.5h.5c.69 0 1.25-.56 1.25-1.25V9.754a1.75 1.75 0 0 1 1.27-1.682L13.27 8l-.25-.072a1.75 1.75 0 0 1-1.27-1.682V4.75c0-.69-.56-1.25-1.25-1.25H10a.75.75 0 0 1-.75-.75"/>
</symbol>`;
const dt_json = ft_json.replaceAll(
  'file-tree-builtin-file-type-json',
  'file-tree-builtin-duo-tone-json'
);

const ft_markdown = `<symbol id="file-tree-builtin-file-type-markdown" viewBox="0 0 16 16">
  <path fill="currentColor" d="M1 12V4h2l2 2.5L7 4h2v8H7V7.5l-2 2-2-2V12zm9-3 3 3.5L16 9h-2V4h-2v5z"/>
</symbol>`;
const dt_markdown = ft_markdown.replaceAll(
  'file-tree-builtin-file-type-markdown',
  'file-tree-builtin-duo-tone-markdown'
);

const ft_mcp = `<symbol id="file-tree-builtin-file-type-mcp" viewBox="0 0 16 16">
  <path fill="currentColor" d="M9.255-.04a2.88 2.88 0 0 1 2.006.815 2.75 2.75 0 0 1 .803 2.36 2.87 2.87 0 0 1 2.406.787l.033.033a2.744 2.744 0 0 1 0 3.934L8.698 13.58a.2.2 0 0 0-.04.06.2.2 0 0 0-.014.07q0 .038.013.072.015.035.041.06l1.193 1.17a.55.55 0 0 1 0 .786.577.577 0 0 1-.802 0l-1.193-1.17a1.28 1.28 0 0 1 0-1.835L13.7 7.102a1.65 1.65 0 0 0 .37-1.82 1.7 1.7 0 0 0-.37-.54l-.033-.033a1.725 1.725 0 0 0-2.404-.002L6.48 9.397l-.066.065a.576.576 0 0 1-.926-.18.55.55 0 0 1 .123-.606L10.46 3.92a1.645 1.645 0 0 0-.002-2.358 1.727 1.727 0 0 0-2.407 0L1.635 7.855a.577.577 0 0 1-.802 0 .55.55 0 0 1 0-.787L7.25.775a2.88 2.88 0 0 1 2.005-.814"/>
  <path fill="currentColor" d="M9.256 2.186a.57.57 0 0 1 .523.342.55.55 0 0 1 0 .427.6.6 0 0 1-.123.18L4.91 7.79a1.647 1.647 0 0 0 0 2.36 1.726 1.726 0 0 0 2.406 0l4.747-4.655a.576.576 0 0 1 .925.18.55.55 0 0 1-.123.607L8.12 10.937a2.877 2.877 0 0 1-4.01 0 2.75 2.75 0 0 1-.616-3.035 2.8 2.8 0 0 1 .615-.9L8.854 2.35a.58.58 0 0 1 .402-.163"/>
</symbol>`;
const dt_mcp = ft_mcp.replaceAll(
  'file-tree-builtin-file-type-mcp',
  'file-tree-builtin-duo-tone-mcp'
);

const ft_npm = `<symbol id="file-tree-builtin-file-type-npm" viewBox="0 0 16 16">
  <path fill="currentColor" d="M2 1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zm11 12h-2.5V5.5H8V13H3V3h10z"/>
</symbol>`;
const dt_npm = ft_npm.replaceAll(
  'file-tree-builtin-file-type-npm',
  'file-tree-builtin-duo-tone-npm'
);

const ft_react = `<symbol id="file-tree-builtin-file-type-react" viewBox="0 0 16 16">
  <path fill="currentColor" d="M8 6.648c.725 0 1.312.605 1.313 1.352 0 .746-.588 1.351-1.313 1.351S6.688 8.746 6.688 8c0-.747.587-1.352 1.312-1.352"/>
  <path fill="currentColor" fill-rule="evenodd" d="M8 2.551c1.296-.99 2.585-1.339 3.5-.795.915.545 1.266 1.868 1.08 3.52C14.063 5.936 15 6.91 15 8c0 1.088-.938 2.063-2.42 2.723.186 1.652-.165 2.976-1.08 3.52-.915.545-2.204.196-3.5-.795-1.296.99-2.585 1.34-3.5.796-.915-.545-1.267-1.869-1.082-3.52C1.938 10.061 1 9.087 1 8s.937-2.063 2.418-2.724C3.233 3.624 3.585 2.3 4.5 1.756s2.204-.195 3.5.795m-3.744 8.644c-.079 1.349.286 2.033.681 2.268s1.154.219 2.249-.525l.117-.084a11.6 11.6 0 0 1-1.245-1.391 11 11 0 0 1-1.791-.415q-.007.075-.011.147m7.476-.147c-.55.18-1.151.32-1.79.415-.4.523-.82.99-1.246 1.391l.118.084c1.095.744 1.853.76 2.249.525.395-.235.76-.92.681-2.268zm-3.04.539a14 14 0 0 1-1.384 0q.344.384.692.701.347-.316.691-.701M8 5.297q-.764.001-1.468.085A13.4 13.4 0 0 0 5.065 8a13.5 13.5 0 0 0 1.467 2.617 12.5 12.5 0 0 0 2.935 0A13.3 13.3 0 0 0 10.934 8a13.5 13.5 0 0 0-1.467-2.618A13 13 0 0 0 8 5.296m-3.362 3.88q-.151.5-.244.967.44.152.936.266a15 15 0 0 1-.692-1.233m6.724 0a15 15 0 0 1-.693 1.233q.496-.114.936-.266a10 10 0 0 0-.243-.967m-7.92-2.92C2.267 6.861 1.874 7.53 1.874 8s.393 1.138 1.566 1.742l.128.063c.125-.58.307-1.188.547-1.805a12 12 0 0 1-.547-1.806q-.065.03-.128.063m8.988-.063c-.125.58-.307 1.188-.547 1.806.24.617.422 1.225.547 1.805q.065-.03.129-.063C13.732 9.138 14.125 8.47 14.125 8s-.393-1.139-1.566-1.743zm-7.1-.605q-.496.114-.936.266.093.469.244.967A15 15 0 0 1 5.33 5.59m5.34 0a15 15 0 0 1 .692 1.233q.15-.498.243-.967-.44-.151-.936-.266M7.185 3.062c-1.095-.744-1.853-.76-2.248-.525s-.76.92-.682 2.268l.01.145a11 11 0 0 1 1.792-.413c.4-.524.819-.99 1.245-1.392zm3.877-.525c-.396-.235-1.154-.219-2.249.525l-.118.083c.426.402.846.868 1.245 1.392.64.094 1.241.234 1.791.413l.012-.145c.079-1.349-.286-2.033-.681-2.268M8 3.711a10 10 0 0 0-.692.701 14 14 0 0 1 1.383 0 10 10 0 0 0-.691-.7" clip-rule="evenodd"/>
</symbol>`;
const dt_react = ft_react.replaceAll(
  'file-tree-builtin-file-type-react',
  'file-tree-builtin-duo-tone-react'
);

const ft_typescript = `<symbol id="file-tree-builtin-file-type-typescript" viewBox="0 0 16 16">
  <path fill="currentColor" d="M8 1c5.765 0 7 1.236 7 7s-1.235 7-7 7-7-1.235-7-7 1.236-7 7-7m2.313 4c-1.773 0-2.16.297-2.16 1.62 0 1.152.387 1.476 2.178 1.863.99.216 1.206.405 1.206 1.062 0 .71-.216.855-1.206.855-.999 0-1.242-.135-1.278-.756h-.945c-.027 1.358.36 1.656 2.15 1.656 1.837 0 2.242-.315 2.242-1.755 0-1.269-.387-1.62-2.151-1.998-1.017-.225-1.242-.396-1.242-.918 0-.603.225-.738 1.224-.738.873 0 1.08.099 1.098.53h.954C12.347 5.262 11.978 5 10.313 5M3.5 5.09v.9h1.611v5.22h.98V5.99h1.62v-.9z" opacity=".2"/>
  <path fill="currentColor" fill-rule="evenodd" d="M8 1c5.765 0 7 1.236 7 7s-1.235 7-7 7-7-1.235-7-7 1.236-7 7-7m2.313 4c-1.773 0-2.16.297-2.16 1.62 0 1.152.387 1.476 2.178 1.863.99.216 1.206.405 1.206 1.062 0 .71-.216.855-1.206.855-.999 0-1.242-.135-1.278-.756h-.945c-.027 1.358.36 1.656 2.15 1.656 1.837 0 2.242-.315 2.242-1.755 0-1.269-.387-1.62-2.151-1.998-1.017-.225-1.242-.396-1.242-.918 0-.603.225-.738 1.224-.738.873 0 1.08.099 1.098.53h.954C12.347 5.262 11.978 5 10.313 5M3.5 5.09v.9h1.611v5.22h.98V5.99h1.62v-.9z" clip-rule="evenodd"/>
</symbol>`;
const dt_typescript = `<symbol id="file-tree-builtin-duo-tone-typescript" viewBox="0 0 16 16">
  <path fill="currentColor" d="M8 1C2.236 1 1 2.236 1 8s1.236 7 7 7 7-1.235 7-7-1.235-7-7-7" class="bg" opacity=".2"/>
  <path fill="currentColor" d="M8.108 9.644h.945c.036.621.279.756 1.278.756.99 0 1.206-.144 1.206-.855 0-.657-.216-.846-1.206-1.062-1.791-.387-2.178-.711-2.178-1.863 0-1.323.387-1.62 2.16-1.62 1.665 0 2.034.261 2.07 1.422h-.954c-.018-.432-.225-.531-1.098-.531-.999 0-1.224.135-1.224.738 0 .522.225.693 1.242.918 1.764.378 2.151.729 2.151 1.998 0 1.44-.405 1.755-2.241 1.755-1.791 0-2.178-.297-2.151-1.656M5.111 11.21V5.99H3.5v-.9h4.212v.9h-1.62v5.22z"/>
</symbol>`;

const fileTypeSetSymbols = [
  ft_css,
  ft_default,
  ft_git,
  ft_image,
  ft_javascript,
  ft_json,
  ft_markdown,
  ft_mcp,
  ft_npm,
  ft_react,
  ft_typescript,
];

const duoToneSetSymbols = [
  dt_css,
  dt_default,
  dt_git,
  dt_image,
  dt_javascript,
  dt_json,
  dt_markdown,
  dt_mcp,
  dt_npm,
  dt_react,
  dt_typescript,
];

function appendSymbols(spriteSheet: string, symbols: string[]): string {
  if (symbols.length === 0) return spriteSheet;
  return spriteSheet.replace('</svg>', `\n  ${symbols.join('\n  ')}\n</svg>`);
}

const BUILT_IN_SVG_SPRITE_SHEETS: Record<FileTreeBuiltInIconSet, string> = {
  simple: SIMPLE_SVG_SPRITE_SHEET,
  'file-type': appendSymbols(SIMPLE_SVG_SPRITE_SHEET, fileTypeSetSymbols),
  'duo-tone': appendSymbols(SIMPLE_SVG_SPRITE_SHEET, duoToneSetSymbols),
};

const BUILT_IN_FILE_NAME_TOKENS: Partial<Record<string, BuiltInFileIconToken>> =
  {
    '.gitattributes': 'git',
    '.gitignore': 'git',
    '.gitkeep': 'git',
    '.gitmodules': 'git',
    '.npmignore': 'npm',
    '.npmrc': 'npm',
    'package-lock.json': 'npm',
    'package.json': 'npm',
    'readme.md': 'markdown',
  };

const BUILT_IN_FILE_EXTENSION_TOKENS: Partial<
  Record<string, BuiltInFileIconToken>
> = {
  avif: 'image',
  bmp: 'image',
  cjs: 'javascript',
  css: 'css',
  cts: 'typescript',
  gif: 'image',
  icns: 'image',
  ico: 'image',
  jpeg: 'image',
  jpg: 'image',
  js: 'javascript',
  json: 'json',
  json5: 'json',
  jsonc: 'json',
  jsonl: 'json',
  jsx: 'react',
  less: 'css',
  markdown: 'markdown',
  mcp: 'mcp',
  md: 'markdown',
  mdx: 'markdown',
  'mdx.tsx': 'markdown',
  mjs: 'javascript',
  mts: 'typescript',
  png: 'image',
  postcss: 'css',
  sass: 'css',
  scss: 'css',
  styl: 'css',
  svg: 'image',
  tif: 'image',
  tiff: 'image',
  ts: 'typescript',
  tsx: 'react',
  webp: 'image',
};

const COLORED_ICON_SET_PALETTES = new Set<FileTreeBuiltInIconSet>([
  'file-type',
  'duo-tone',
]);

export function getBuiltInSpriteSheet(
  set: FileTreeBuiltInIconSet | 'none'
): string {
  const builtInSet = set === 'none' ? 'simple' : set;
  return BUILT_IN_SVG_SPRITE_SHEETS[builtInSet];
}

export function getBuiltInFileIconName(
  set: FileTreeBuiltInIconSet,
  token: BuiltInFileIconToken
): string {
  return `file-tree-builtin-${set}-${token}`;
}

export function isColoredBuiltInIconSet(
  set: FileTreeBuiltInIconSet | 'none'
): boolean {
  return set !== 'none' && COLORED_ICON_SET_PALETTES.has(set);
}

export function resolveBuiltInFileIconToken(
  set: FileTreeBuiltInIconSet | 'none',
  fileName: string,
  extensionCandidates: string[]
): BuiltInFileIconToken | undefined {
  if (set === 'simple' || set === 'none') {
    return undefined;
  }

  const lowerFileName = fileName.toLowerCase();
  const exactMatch = BUILT_IN_FILE_NAME_TOKENS[lowerFileName];
  if (exactMatch != null) {
    return exactMatch;
  }

  for (const extension of extensionCandidates) {
    const match = BUILT_IN_FILE_EXTENSION_TOKENS[extension];
    if (match != null) {
      return match;
    }
  }

  return 'default';
}
